spring.application.name=buscadorjava

# --- Configuração do Banco de Dados (Neon) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- Hibernate & JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# --- API Adzuna ---
adzuna.api.base-url=https://api.adzuna.com/v1/api
adzuna.api.id=${ADZUNA_API_ID}
adzuna.api.key=${ADZUNA_API_KEY}

# --- Performance & Infra ---
spring.threads.virtual.enabled=true

# O Render atribui uma porta dinâmica; se não houver, usa 8080
server.port=${PORT:8080}